### ISSUE TITLE
This line is probably not needed

### ISSUE THREAD

**Issue by ddziaduch** [ardalis/DDD-NoDuplicates#4]
I am a PHP dev, never code in C#.

But this line looks like a copy-paste from previous example, seems to be unused:
https://github.com/ardalis/DDD-NoDuplicates/blob/9b4c308de948cd1a678cdf616fac96c13d4540bb/NoDuplicatesDesigns/10_AggregateWithMediatR/Catalog.cs#L18

Or maybe I am wrong :)

**Comment by ardalis** [comment]
Yep, looks like it, agreed. 👍

**Comment by ddziaduch** [comment]
Seems to be sorted :)
